# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './window/mainlayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 750)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(770, 400, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.recognition_button = QtWidgets.QPushButton(Form)
        self.recognition_button.setGeometry(QtCore.QRect(510, 470, 151, 31))
        self.recognition_button.setObjectName("recognition_button")
        self.clear_button = QtWidgets.QPushButton(Form)
        self.clear_button.setGeometry(QtCore.QRect(510, 520, 151, 31))
        self.clear_button.setObjectName("clear_button")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(510, 570, 151, 31))
        self.save_button.setObjectName("save_button")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 20, 791, 41))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.choose_model_button = QtWidgets.QPushButton(Form)
        self.choose_model_button.setGeometry(QtCore.QRect(340, 520, 151, 31))
        self.choose_model_button.setObjectName("choose_model_button")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 20, 741, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 751, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(60, 150, 441, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(60, 230, 441, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(60, 270, 441, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(60, 310, 441, 31))
        self.label_8.setObjectName("label_8")
        self.train_button = QtWidgets.QPushButton(Form)
        self.train_button.setGeometry(QtCore.QRect(340, 470, 151, 31))
        self.train_button.setObjectName("train_button")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(60, 110, 441, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(130, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.result_area = QtWidgets.QLabel(Form)
        self.result_area.setGeometry(QtCore.QRect(700, 450, 231, 231))
        font = QtGui.QFont()
        font.setPointSize(120)
        self.result_area.setFont(font)
        self.result_area.setStyleSheet("*{\n"
"    background:white\n"
"}\n"
"")
        self.result_area.setText("")
        self.result_area.setAlignment(QtCore.Qt.AlignCenter)
        self.result_area.setObjectName("result_area")
        self.image_area = QtWidgets.QLabel(Form)
        self.image_area.setGeometry(QtCore.QRect(70, 450, 231, 231))
        font = QtGui.QFont()
        font.setPointSize(120)
        self.image_area.setFont(font)
        self.image_area.setStyleSheet("")
        self.image_area.setText("")
        self.image_area.setAlignment(QtCore.Qt.AlignCenter)
        self.image_area.setObjectName("image_area")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 450, 231, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.data_area = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.data_area.setContentsMargins(0, 0, 0, 0)
        self.data_area.setSpacing(0)
        self.data_area.setObjectName("data_area")
        self.choose_paint_button = QtWidgets.QPushButton(Form)
        self.choose_paint_button.setGeometry(QtCore.QRect(340, 620, 151, 31))
        self.choose_paint_button.setObjectName("choose_paint_button")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(60, 190, 431, 31))
        self.label_11.setObjectName("label_11")
        self.choose_image_button = QtWidgets.QPushButton(Form)
        self.choose_image_button.setGeometry(QtCore.QRect(340, 570, 151, 31))
        self.choose_image_button.setObjectName("choose_image_button")
        self.probability_text = QtWidgets.QLabel(Form)
        self.probability_text.setGeometry(QtCore.QRect(700, 700, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.probability_text.setFont(font)
        self.probability_text.setStyleSheet("")
        self.probability_text.setText("")
        self.probability_text.setAlignment(QtCore.Qt.AlignCenter)
        self.probability_text.setObjectName("probability_text")
        self.quit_button = QtWidgets.QPushButton(Form)
        self.quit_button.setGeometry(QtCore.QRect(510, 620, 151, 31))
        self.quit_button.setObjectName("quit_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "识别结果"))
        self.recognition_button.setText(_translate("Form", "识别"))
        self.clear_button.setText(_translate("Form", "清空"))
        self.save_button.setText(_translate("Form", "保存"))
        self.choose_model_button.setText(_translate("Form", "选择模型"))
        self.label_3.setText(_translate("Form", "手写数字识别系统使用说明"))
        self.label_4.setText(_translate("Form", "训练模型：可以对训练参数进行设定，包括模型训练的批次，轮次，学习率等"))
        self.label_5.setText(_translate("Form", "选择图片：可以识别本地图片"))
        self.label_6.setText(_translate("Form", "识别：对图片进行识别"))
        self.label_7.setText(_translate("Form", "查看模型参数：查看当前模型的参数"))
        self.label_8.setText(_translate("Form", "保存：保存手写板上面的图片"))
        self.train_button.setText(_translate("Form", "训练模型"))
        self.label_9.setText(_translate("Form", "选择模型：选择已经训练的模型或者默认模型"))
        self.label_10.setText(_translate("Form", "图片/手写板"))
        self.choose_paint_button.setText(_translate("Form", "手写板"))
        self.label_11.setText(_translate("Form", "手写板：点击后可以在手写板上写数字"))
        self.choose_image_button.setText(_translate("Form", "选择图片"))
        self.quit_button.setText(_translate("Form", "退出"))

